image: cirrusci/flutter:stable

stages:
  - analyze
  - test
  - build

cache:
  paths:
    - .pub-cache
    - build/

before_script:
  - flutter pub get

analyze:
  stage: analyze
  script:
    - flutter analyze

test:
  stage: test
  script:
    - flutter test

build_apk:
  stage: build
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk